0=Infobar (global Size)=infobar-fields.png
1=Infobar=infobar-fields.png
2=Infobar=infobar-fields.png
3=Infobar=infobar-fields.png
4=Infobar (global CPU)=infobar-fields.png
5=Infobar (global HDD)=infobar-fields.png
6=Infobar (global)=infobar-fields.png
7=Infobar=infobar-fields.png
8=Infobar=infobar-fields.png
9=Infobar=infobar-fields.png
10=Infobar=infobar-fields.png